controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
list_items:
    path: /list
    methods: GET
    controller: App\Controller\TodoController::listItems
save_items:
    path: /save_items
    methods: POST
    controller: App\Controller\TodoController::addItems
delete_items:
    path: /delete_items
    methods: POST
    controller: App\Controller\TodoController::deleteItems
