controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
list_items:
    path: /list
    methods: GET
    controller: App\Controller\TodoController::listItems
save_items:
    path: /save_items
    methods: POST
    controller: App\Controller\TodoController::addItems
delete_items:
    path: /delete_items
    methods: POST
    controller: App\Controller\TodoController::deleteItems
sign_up:
    path: /sign_up
    methods: POST
    controller: App\Controller\SignUpController::signUp
log_in:
    path: /log_in
    methods: GET
    controller: App\Controller\LoginController::logIn
log_in_check:
    path: /log_in_check
    methods: [GET, POST]
    controller: App\Controller\LoginController::logInCheck
log_out:
    path: /log_out
    methods: [GET, POST]
    controller: App\Controller\LoginController::logOut
table:
    path: /table
    methods: [GET, POST]
    controller: App\Controller\TableController::showSkillsFromAllUsers
some_users_todo:
    path: /some_users_todo
    methods: [GET, POST]
    controller: App\Controller\SomeUsersTodoController::showSomeUsersTodo
    
