controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
list_items:
    path: /list
    methods: [GET, POST]
    controller: App\Controller\TodoController::listItems
save_items:
    path: /save_items
    methods: [GET, POST]
    controller: App\Controller\TodoController::addItems
delete_items:
    path: /delete_items
    methods: POST
    controller: App\Controller\TodoController::deleteItems
edit_items:
    path: /edit_items
    methods: POST
    controller: App\Controller\TodoController::editItems
sign_up:
    path: /sign_up
    methods: POST
    controller: App\Controller\SignUpController::signUp
log_in:
    path: /log_in
    methods: GET
    controller: App\Controller\LoginController::logIn
log_in_check:
    path: /log_in_check
    methods: [GET, POST]
    controller: App\Controller\LoginController::logInCheck
log_out:
    path: /log_out
    methods: [GET, POST]
    controller: App\Controller\LoginController::logOut
table:
    path: /table
    methods: [GET, POST]
    controller: App\Controller\TableController::showSkillsFromAllUsers
some_users_todo:
    path: /some_users_todo
    methods: [GET, POST]
    controller: App\Controller\SomeUsersTodoController::showSomeUsersTodo
add_users_photo:
    path: /add_users_photo
    methods: [GET, POST]
    controller: App\Controller\AddUsersPhotoController::addUsersPhoto
add_url:
    path: /add_url
    methods: [GET, POST]
    controller: App\Controller\AddUsersPhotoController::addUrl
delete_account:
    path: /delete_account
    methods: [ GET, POST ]
    controller: App\Controller\AddUsersPhotoController::deleteAccount
forgot_email:
    path: /forgot_email
    methods: [ GET, POST ]
    controller: App\Controller\LoginController::forgotEmail
send_forgot_email:
    path: /send_forgot_email
    methods: [ GET, POST ]
    controller: App\Controller\LoginController::sendForgotEmail
reset_page:
    path: /reset_page
    methods: [ GET, POST ]
    controller: App\Controller\LoginController::resetPage
reset_type_new_password:
    path: /reset_type_new_password
    methods: [ GET, POST ]
    controller: App\Controller\LoginController::resetTypeNewPassword
    
