# config/services.yaml
parameters:
# ...

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    PDO:
        class: PDO
        arguments:
            - 'sqlite:./sk.db'
        
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/*'
            - '../src/Service/*'
            - '../src/Kernel.php'
    
    App\Service\:
        resource: '../src/Service/*'
